require: rubocop-rails
Rails:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/UnknownEnv:
  Enabled: false
